#pragma once
std::string agumon =
"                                           .::L7r7rrJr:                                   \n"
"                                         :;;::::,,.,,:;r;, ..                             \n"
"                                    r7vcsr;:::::::;:::::;7L7vLU                           \n"
"                                   cv::::;:;:;:;:::::;:;::::::c7                          \n"
"                                  ;Or:,:::::;:::;:::::::::::::rX                          \n"
"                                  Ew.Kw,:::;:;:::::;:::;:::::,GZ                          \n"
"                                  2;rQ7v,:::::::;:::::::::::::Z,     ..,::;rr;7c:,:;;r:   \n"
"                                 .2.SO ,v.:::::::::::::;::::.v1g .;7Lc77r7rr;rsgi:rric:   \n"
"                                 ;L.7gDBB:,:r;::;:::;:::;:7r.DBQPrr;::::::::::;::;r2r..   \n"
"                    ,:;i7LvcLv7; L7,,GHRQK.7r::;:::;::::::;r,O2;77.:::::::::::,;r::S2,;LU,\n"
"                .;sLsr7;;:::::;irPc.,,;.Js,:::::::::::;::::::,, c7:r7;::::::::::LSs7:::,r,\n"
"             .rUL7;:,:::::::::::.r6.::,:,::::::::::::::;:::::,::DpK5sX66aaXwJ1sL;Gv       \n"
"           rUX2;::,:r::::::::::7:.2r,iw::::::::::,::::;:::::,,SZE:        .:JJU2MH;rPX    \n"
"        ;sgZJ;.:,,rp;:::::;7JaMR5J;J:.iJ.:::::;JrL:::;:::::;2LEQ                   .,,    \n"
"      :cDUL.,2v;;wp,:rr:,rQcr  .:;LUOr,vsr;,:::;7LX::::::::UL;;M                          \n"
"     s:r7.   :B1SMrri;.P1H         E6Uv5v:7J,:::,:::::::::::, 7B                          \n"
"   .P.c7 ..:rsRc: P.  ,RU         c17EsLa:.K5,,,::::::::::::,rBD                          \n"
"   Z ;1 ,r7r,    ;; :J7           gLr;JUUga:;Z7, . . .....,:rMs:J                         \n"
"  LL,Q:7L:       QrLL.           :B7:.,:;iss,:BBBE6EgRBBBB1L;,,.H.                        \n"
"  7K:;;.         :;.              GL::::,,,:5;.EaOBBBBBB7RsX,,,:E:  ,i;7                  \n"
"                                  :O;.:::::::J7:::cvv7c;;L:.a.:rE :vr,LS                  \n"
"                                  ;2K:,::::::,:rr::;:;::57  25LHX;:...a    ..,..          \n"
"                                 v7 BEL:,,:::::,,,:,,.,2w . rZJ:s;   rr .;7r;ig;          \n"
"                                7s:,;ZXX17;;::;r;rrrr7JLL,  iM7.i5sr;6LcJ   :s.           \n"
"                                K:::,:Js2Pg5HpJ7wcJr7P5 7H2J1cKrL7LsLHJ;a;.;U             \n"
"                               cs:::::.:rvr77P       HU.;L77iJH77v7rwKrc72KB              \n"
"                               Jr::::::;L7sr7a,     :R;,:7c77rsv777r1777c61.              \n"
"                               Pi::J,:,icJrvrE,     2D,:vs77r7r7rv77r77JG7                \n"
"                               27rSS,,,iEs.LLg.     ,B,;s77777v7v7777cHS,                 \n"
"                               L,s.;XL1EUJ7LZw       L777777777v7777wp:                   \n"
"                               .S:  X,;a  1.S        .1rv7777777777Ha                     \n"
"                                    .ss.  .w:         XJvv777v777JZs                      \n"
"                                                       5E5JLLL1wpK:                       \n"
"                                                         .,;;::.                          \n";
std::string greymon =
"                           :                                                              \n"
"                          ;Q                                                              \n"
"                          Bv                                                              \n"
"                         UBv                                                              \n"
"                         QBBc                                                             \n"
"                          HBBBK:                                      :J                  \n"
"                            6BBBMv,                                  7B:                  \n"
"                              vBBBBps:                             .ZBS                   \n"
"                                ,gBBBBOLJBBQBg2:rs21L:            rQBB                    \n"
"                                   LBBBMOBBQBBBBBBBBBBM.        ,UQBg. U                  \n"
"                                     rBBBZ  ;BRBBOgDgRBBwOQg:  rEBBs: Qr                  \n"
"                                  SQRDS6Q;:ZBRgBGOODOBBBKQQBQrJQBBSZGBr                   \n"
"                                 ,gBZsJpBg5OBgQDgMBQBBBBBgRcrXBBBpBBB:                    \n"
"                                :OJ5PRBQDQQMGOZD6J7r::;isL:1QBBBgr                        \n"
"                               :ZpMOMDgRMgBGGEDgs:rrJ56ZgaMBBO6c                          \n"
"                         ;7LLc7HrJ;,,LJvwPsBOgOgRBQBBQRRDRDggOgi                          \n"
"                       .1s7rr:;s;2:,,swL1 .BBBBgDGgGDGOEDGG6MQBB.         ..::::iir7ccJ:  \n"
"        :;.         :7s57;;;:csc:17;JJcBPRBB5 :BBBMOGgGDEOZOQQBB:  .,7p2rJ1215aZZOZSs7;.  \n"
"       HU7U5: ,;rrrcJsLr;rLs1gB;s5UB;;pgBRXg:rPMBs2BBQBBBBBBBBBB,,vLsLXBZc2aH2s;,         \n"
"       7a, ,QXJL77rrsa;L1r.EsrBZ,c2RL,LHQ. BBBOBL rBQ ,ZaMpQBBB2:rrsr7rRBsr:              \n"
"        5S7  2rwZ1wJKPc;  :pr,LRD7;6BrOr7 .BBsgDHpQgg ;rU,  ::H.:r7SQ251                  \n"
"    :7v2w77H7vJ2.  UP    :6JJ:,:vpr:vcQw.iZB, BDRBEgZr,UXr::r;UGZ7;sBL                    \n"
"    g5:;ZHcU1ES;.,L7    rL7Lccri;;rirrLHaR;J,:BBO:ORESE,scJJ;iir6BZc      ..              \n"
"    ,5, rpD2sJ:,       RBcrJw2UsL7rrr;::cBs,7XGX .BBHH .J771JwsviR;   :vJsv1KL            \n"
"      ....;           cpMDPU5wc::;;;i;r7rUDr;:i:,JUwSv.sasLr7i77sr:r7J2r1svi U            \n"
"                     :L,,::;:::;;i;r;ircLsHQHw7rrri7JUcL1s;;:::::LPsvc1GssUs ,s           \n"
"                     rpJDKSL;;i;r;r;i;;:;,,ipgQgMGU7sXvJcr6K77crJ77:;. ,v7cJ7751s         \n"
"                     5BGv;:;;r;i;i;r;i;r2aUr.,:;77:;;7rcRrJBHU:rU6HRPMOL7pXpGs;SR         \n"
"                    11r::;i;r;r;i;i;r;r;::cGR7::r;7PREHrRwQM,     :;ri:icr: r 7S.         \n"
"                  .UBg6R::;i;i;r;r;r;r;r;;::2MgQQBMEK6SPQJ                 wc7;           \n"
"                 ;BX;:;SK::;i;r;i;i;r;i;r;i;::rc6wHHXsJUpp                ::.             \n"
"                 KJRQMZJcKc::;;;;;;;;;;i;;:;;rr7;D2;,::c7JZ.                              \n"
"               ,a;::irswHXSS1ri;;;r;i;i;rr77sspsLX,:r:;:rsps                              \n"
"               Pv;7r:;;;;;7P2KsJs2US222SUXXKJ;1ar::w;;;;::pr                              \n"
"               :KJXarLLLsscrwL7LH.:;irr;:,.    :vL71:;r;;:E                               \n"
"                 ;;r:LsscswEs;7ss               :U:Jr;:;rsO                               \n"
"                     7r7J;i::;vU.               K;;;777Lw1L                               \n"
"                .Lw7JKLv;;rLssLO:              :2;;;;rrr7sL                               \n"
"              :;;:Swr. 7LJgJ; vD7             cU7r777;::7L6:                              \n"
"             Lrc7rU; ;r7Kcra  cB,            Xs;rsi;;;rsc7sJs: .                          \n"
"            s5r,  7;Ji,    :. H             ,g7;LJsc;;c;7;rXD252HP7                       \n"
"                  Lr        i77              Brs.:J5s;:7;   LP7c; r7:                     \n"
"                             ,               E2   vHg172.    ;wU;   :7;                   \n"
"                                             sR   ;g:;2Ocs7: .sXrcsv,.L7                  \n"
"                                              .;, w;     ,rJv:2    ,r7c6                  \n"
"                                                ;iU         ,rJ        .                  \n"
"                                                 .                                        \n";
std::string metalGreymon =
"                                                           7                              \n"
"         7                                                H,                              \n"
"         rBQK;                                           MB                               \n"
"          LBRBRS,                                       KBr                               \n"
"           LBpZgBDs:                              .    6BQ                                \n"
"            LQPKERRBDc                            B,  EBB2                                \n"
"    Eg7.     7BEr7RGgBE:            .            cBv 7BEB                :                \n"
"     LQBMU;   7BU .6gORB6:,         5:     ::    QBJ MKBX               .B                \n"
"       ;BBBMr   ;E; :SpPgBBQ7       Qi     rB   ;BR65GMB                BZ                \n"
"         SRGgQQK;;66rUSaaX6QQR.     B5  :  LBs.:UO6JZOQc              :XB7                \n"
"          QBDHp;KQBBgHHSaS5SEQBJ    RBr cZ,JBQ6Kwc;,:::;ss7:.         BBp,                \n"
"           cBBRc  .GQPJ6UUUSwSDBBs   rsKX7sD;7c16Xs7rr7vJJJ2Jc:   .,,PQQJ                 \n"
"             ;BBQ:.vpv  EX21U5s1MBQ7    ;QBg1JQpDXpGZsccUXc7Js21HaBLSBBp;                 \n"
"                RBBGKggaZDE6SHw1UGBBRBOPUEpG6QQQR5ODsBPc;cs;:rcs77, XBPL,                 \n"
"        .iXE5r:.,:EBQDggDEDggOgEX26gE6s.aDGDDg6.UKQU:DDKpLrrr:;7LLKBQZ7,                  \n"
"           sQBBBBB;:wRgDEDZEZOEgggDBBEODZ6XXJQ6;wpXOggSHHZPU7r:i2gDRQpr                   \n"
"               pBBg7sgQRMRRgMgRggMQDaJHRpJLcUpp2PZBUJJHEZXEOKr7r;r777ri:                  \n"
"            .    :5BQGEQBBBBBBRRBO;:::,151JJ5:JZvJBB5iDi2G6PDX;7rr;r;:7J                  \n"
"        ;7JPpaSs7:::;           rrr;::iPXJKsS;7G7rJiOQDrE:a6RBJr7r7rrcB;                  \n"
"    .r26GggZKHUPG2rr:r77.   .;r7rr;s115OX5X6SJaarE:7s7RE5D6: ,2X5ULsXBw                   \n"
"   7RQQgGpEaXQBBOJUPHrJ1UOc7Xwi:;rJ5ZZDXsrc7ap2sHgr1;K:2EQBL     :XXB2                    \n"
"  EBPr        :pGP15RBRXEPrr:LZDRUO1wQRc:::Jr7sUsJwBL;:B2cBBS,                            \n"
":JU.             HKJSgOZO7rsc;SPRU5LDRU;LRO.;v772JsUscr7.,MBUO,                           \n"
"                  6SsLLs6s,:sLrsv2UJZ6:rPO: ;riss7rrsL57w7irr,                            \n"
"                  LE22UsZg; ;Lrcr:sXJsc2B7 ;JLJPJr;c7Zw;RZ,                               \n"
"                   HEGr;UOwLsSw6s:.GgKU5X5spavJ7rPv25BBG717:,,.,.                         \n"
"                    wBJ.,s1RBRBGQ .6g6ULJ5XZPr775s2LEXsswLsS6PXs7vsv:                     \n"
"                     ;S7.PBPJJJc7aXpc7swJ7rLL7;7srRMr:;66aLrr77U52rrc527,                 \n"
"                        651JPZDXv;HOpUUv7;;;i;;rJOJr7vB5::;iv2KcrcU;.;7L2s;               \n"
"                       .SggMOgRXspQPHw;::rr7csaB2r:::as:;r;r;;rHRE;26s77v11J:             \n"
"                      UHDOsLsss::cBPZppXKHK1rrapOZac7;;;;;rrrr;,JSXp;;21777r77J:          \n"
"                    ;DKw1as12s;;rc:;cJLv;,        .HEE6ZH2772s;rKaBc;;rJ:r7v7arJs:        \n"
"                   JgP2JUaJ2r:;rsr                sX2rvsSJr7UcsLEcBBBMgEi;;rDBr;cJc:      \n"
"                  sRE1swUPPZUSaZ2                XP1:::i;7v17:     ::;7OE1r;;gDXvrrL1r    \n"
"                  ;EpXXUw1J:;rvr               ;pKXJcJKUsLv,            :2EUr:,rDDSrrEgJ. \n"
"                  rEcw1v;i:                 :HDES215aKs,                   JEPr  :SgSc::X;\n"
"                  6r;1;:v7r,              rRgga1UUaSHX                       rgX    7Dg  ,\n"
"                .UJr7Hr71OvsL::,          rBG6SS2Jc77sr;,                      ,      s:  \n"
"              .av;srp21: :gwL5r::           7XOKv:::i7J1KHssHHUs2v:                       \n"
"              SS  swGQP7; rBQ6rr;;            :SDKs7r7Lr;r71,,LK,:rr,                     \n"
"               .        .                        :r;r7vrrisi,  :r:.,7.                    \n";
std::string warGreymon =
"                                                      ;                                                       \n"
"                                         :            Qr           ..                                         \n"
"                                         gg          ;;c          .B7                                         \n"
"                                         JQ7Zi ,  :1r6,5ssL. ., sXvB,                                         \n"
"                         .                .LB7BB::r7:2r1r:rr,sBsZQ:                 .                         \n"
"                         pr,                   .5B,  Lr5   sBi                    ,7P                         \n"
"                         :7 :wJ,      ..        Qs;. ,;:  ,i62        .       :s2: 7:                         \n"
"                          HgEPw7;7,,.7v::,    :aLPra;:::;cw7X1K. . .,::7;.,:r;r5HGGK                          \n"
"                          .Q,...::. .,.,::ir:vBgJQBBBB6OBBBQU7Ba.:r;::,.:. .:,...,B.                          \n"
"                          .p;:.           1D.;a1ERpEZRMQOEOKQaJ: ;QJ           .:;K.                          \n"
"                         ;O,    . ...   rBG7;.:.LQg6ZEROGP6gBr.:,;L6Bi    .       :E;                         \n"
"                         g7    . .    ,BGppEpM1s:..r11rLUar..;L5RZpEKDB:   . .     7O                         \n"
"                         PJ:          .sHssgJ  ;   pasv;7XX   r  JRc1XJ     . .   :sP                         \n"
"                        ,J;7;       ;JL.7O7   2.   :Zvs2sE.   ,J   :D2.Ls;       ;r;s:                        \n"
"                     .;iSr        71L:sZJ;gs;,iHJ:;KBOLUQQH;;JX;,;s677EU:v1r.      .7ci;.                     \n"
"                     .a;iGQg   :cBi,. :BP:;UDL:;pJ.:MKr;XR.,1H::sgU;.PQ7 ..;gs,  .BBa;7Z                      \n"
"                    .:.  7v, :w7;S .. JBXg, sp: v.  Hp5pM7  ,r :GL  RaRK ., Ur7s: ;LL  .:                     \n"
"                   i:  ,5GMDMa:. U;  vRX2aRw,vG,2a;;ERiiEZ;;SJ,R7.7gH5SM7  :U..:wBMM6s   ;:                   \n"
"                 ;r  .HBQPEBB..,..1sQDJsaXXBZ 5: L: SPJrX6 ;r ;5 UBXH2JsgRJJ,.,..EQEpQBL  .i:                 \n"
"               :i.  JgQM6 ,Ur:,.  .MSUSXs2X;:isX  r EHcaHR r  SJ,Lc2swSX2UQ:   ,:;ar ;BBG7  :r.               \n"
"               K. .Bg2JQr    ,7KBBpQG2agRJ7XOMpGr.L;v1vrsrrr.rOpMZDZUDGUSPBXRBRs:     B1SQR  :2               \n"
"               7c  KD2JB       .rRBBBsZg; rBR6H6RBR6555a2aPRBQpPHQBJ.JgKLOBBBw,       XZJRs  2:               \n"
"                P.  RKPE           rgDa  U;JGXRZXpBRDOgODGRBOX6Dpp5:1 ,EDMU.    .     iQHg  :2                \n"
"                :S   MBs     .       S  ss  X:;SBc;BBBBBBBBs:BSr:X  7s  p      . .     BQ. .H.                \n"
"                 rs   B:    . . .    s :g  rP,,.U: 1irrrr;U  X,,:P; .g. :;    . ..     B:  X:                 \n"
"                  rL  L,    .. . .  r: R; ,M....7r ;      ,,,J ..,g  c6  X   . . .     1  5:                  \n"
"                   ;J 1     . . .   2 PL  M:.,,.;;.U,::::.J:,7.,: LS  Gr s:   . . .    v7s,                   \n"
"                    .J6    ... . . ,rr1  XJ.,:,.:pHMJS5a5wGGSi.:,,.D, .M .s  . . ..    7Z                     \n"
"                      a     . . .  ;wr  ;g.,:,:.,g167cLLLrKwR;.,:,.;G  .S U   . . .    ;i                     \n"
"                      w.   . . .   gs   Q;.:,:,,.E5RsUUS2JZPE:.:,:,.X7  r.;;   . ..    7r                     \n"
"                      H7,   . .   :Q   KU,..,,:,.Z2c  . . rJR.,,,.,.:Q   2G2  . . .   75;                     \n"
"                      KcL.   .    Xv  LB:;.r2... w L,::::,c.L... Lv.,HU  ;Rg   .     7rG,                     \n"
"                      7srL:      .B, rS,1;7rG2::,J:JJsJsJLX.w,::sZ7r:7B; .Oar       c7rS                      \n"
"                      .RvH5s.    77.,:  :DX:,JS17Js;JJsJsJr72rL5J:.JG;.;.,  S     ;KU2US                      \n"
"                      ;rZ. JZr.  a    r7.rJ;, .:K2sL7cLcLrLJsP:. .:Lw.;r    1,  ;5K: prc                      \n"
"                      r ,:  ,wHLrv   J:;.  :Lv::Xv7;      :J;P:,rsi   ;,J,  .J;Sar   L s                      \n"
"                      ;:.r     ;K   s; 2,.   :sp1:;L      cr,r61;   . s: S   LJ.    .7 s                      \n"
"                       X,p:.r1::w  ;J .X: .    :7rsc7    ;L77rr    ,..2r :S  ;v:r1..wrL;                      \n"
"                       L ;. RDgB  Rs:,:2c     .:;sGUrJ  ;2rDSr:,     :S7.::B, JBZB; s J                       \n"
"                       :;G;7ZwZa  .R:,;1S: ::r7sJ7iS5QpERpX7rssLr::. s2r,,51  .B1SE.Q;7                       \n"
"                        ZBMOsJR7    OX, ::;rswXSG5;LRvgBJXE:LGPaaJc;::. 7R;    MUs5BDB.                       \n"
"                         QPQsJR:     6B5:7pZ6Z6ZHB5rQBBBBBJ7BZPE666EX;7MB:     g5sZEM;                        \n"
"                         .BZDsM.      HBBDOZGp66E6Q;E;  ,p7KQp6PZpGEgMBB       EaXRg5                         \n"
"                          ,RQRB:      7gPgGOZG6ZHHg7p,   2LpEHHE6OEOOEXp       BDBM2                          \n"
"                            g;57     ,BZKHGEEZpHDPRcRQs Bg5pDp6aZ6OZ6H6Mr      M.O;                           \n"
"                                .:::,Jc;;;:;:::JpgDLQBs BBKXQGPr:;:::;;rL:;r:,                                \n"
"                              ,rLs;;L::::::::: :aJJrQ:   g27UUJ ::::::::;7rr1v:7                              \n"
"                             ,g;7;iUs::;r7;v;iJ..X77R    JU7U7 7srrr7c7vrsp17SLLJ                             \n"
"                      ,:i;::vJr:;r;,..... rc..,s;,gKP;   vDMv.Sr,..v,,:., ,rr,:;g,                            \n"
"                   :Lwsr,:sZsrr;,,.,,.,r7sP:.,..;;:.;M  :D ;;s:,,,.72,...,,.,7r::ss;:;;;,                     \n"
"                .;;.   Jsrr    ;;.,,.7Gv:,,r;.::...7S.  .Zr ....,.:r1s2s:.:,,..;7;LZJ,,:25J.                  \n"
"               r:      c:       2:..ig      1:.S..H7      ww .r;.;v.  .rQ;.,,,r;   .Lc;J  ,;;:                \n"
"             ,7    ..:1       ..UJ:rR       7s.gLS7        Ec.P.:K      :g...sr       57     :7.              \n"
"             2::r7r77D   .,;rc7sOwvrH    ,;7Z27r,           sJM:cs.      Hw;:G,.       ;r      7;             \n"
"                     7,;rrr;:..     ,r:7L7ir;                  ;1Osr:.   SvLsg177;,     w27i;,. Lr            \n"
"                                     .,.                         .::rsc:r:    .,:r7svr: ;w ::;;;;;            \n"
"                                                                      .,.           ..:::                     \n"
"                                                                                                              \n";

std::string arts[4] = {agumon, greymon, metalGreymon, warGreymon};